/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.stackexcerise.scraping;

import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.AbstractAction;
import javax.swing.RowFilter;
import javax.swing.RowSorter.SortKey;
import javax.swing.SortOrder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;

/**
 *
 * @author Juan Pablo
 */
public class frame extends javax.swing.JFrame {

    StackBuildersExercise scrapWeb = new StackBuildersExercise();
    DefaultTableModel scrapTable;
    TableRowSorter<TableModel> orden;
    DefaultTableModel tablaFiltrada;
    private static final String EMPTY_STRING = "";

    /**
     * Creates new form frame
     */
    public frame() {
        initComponents();
        scrapTable = (DefaultTableModel) scrappingTable.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrapButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        scrappingTable = new javax.swing.JTable();
        jTextUrlScrap = new javax.swing.JTextField();
        jPanel1 = new javax.swing.JPanel();
        jFilterScrap = new javax.swing.JComboBox();
        jSortScrap = new javax.swing.JComboBox();
        jLFilter = new javax.swing.JLabel();
        jLSort = new javax.swing.JLabel();
        jBOperations = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jScrapButton.setText("Scrapping");
        jScrapButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jScrapButtonActionPerformed(evt);
            }
        });

        scrappingTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Rango", "Titulo", "Puntaje", "# comentarios"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        scrappingTable.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_ALL_COLUMNS);
        jScrollPane1.setViewportView(scrappingTable);

        jTextUrlScrap.setText("https://news.ycombinator.com/");
        jTextUrlScrap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextUrlScrapActionPerformed(evt);
            }
        });

        jFilterScrap.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Titulo > 5 palabras", "Titulo <= 5 palabras" }));
        jFilterScrap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFilterScrapActionPerformed(evt);
            }
        });

        jSortScrap.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "# comentarios", "puntaje" }));
        jSortScrap.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jSortScrapActionPerformed(evt);
            }
        });

        jLFilter.setText("Filtro");

        jLSort.setText("Orden");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLFilter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jFilterScrap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 10, Short.MAX_VALUE)
                        .addComponent(jLSort, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jSortScrap, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jFilterScrap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLFilter))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jSortScrap, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLSort)))
        );

        jBOperations.setText("Filtrar-Ordenar");
        jBOperations.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBOperationsActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 685, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextUrlScrap, javax.swing.GroupLayout.PREFERRED_SIZE, 277, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrapButton))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jBOperations)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextUrlScrap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrapButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(jBOperations)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 263, Short.MAX_VALUE)
                .addGap(26, 26, 26))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jScrapButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jScrapButtonActionPerformed
        // TODO add your handling code here:
        LimpiarTablas(scrapTable);
        scrapTable = scrapWeb.Scrapear(jTextUrlScrap.getText().trim(), scrapTable);
        orden = new TableRowSorter<TableModel>(scrapTable);
        scrappingTable.setRowSorter(orden);
    }//GEN-LAST:event_jScrapButtonActionPerformed

    //Método que borra todos los datos de las tablas dentro de la aplicación y de pantalla 
    private void LimpiarTablas(DefaultTableModel tablalimpiar) {
        if (tablalimpiar.getRowCount() > 0) {
            for (int i = tablalimpiar.getRowCount() - 1; i >= 0; i--) {
                tablalimpiar.removeRow(i);
            }
        }
    }

    private void jTextUrlScrapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextUrlScrapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextUrlScrapActionPerformed

    private void jFilterScrapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFilterScrapActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFilterScrapActionPerformed

    private void jSortScrapActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jSortScrapActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_jSortScrapActionPerformed

    private void Filtrar(String filtro) {

    }

    private void jBOperationsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBOperationsActionPerformed
        // TODO add your handling code here:
        String ordentTexto = jSortScrap.getSelectedItem().toString();
        RowFilter<Object, Object> filter = null;
        Integer columnaOrden = 0;
        switch (ordentTexto) {
            case "# comentarios":
                columnaOrden = 3;
                break;
            case "puntaje":
                columnaOrden = 2;
                break;
        }

        switch (jFilterScrap.getSelectedIndex()) {
            case 0:
                filter = new RowFilter<Object, Object>() {
                    public boolean include(RowFilter.Entry entry) {
                        Integer population = entry.getValue(1).toString().split(" ").length;
                        return population.intValue() > 5;
                    }
                };
                break;
            case 1:
                filter = new RowFilter<Object, Object>() {
                    public boolean include(RowFilter.Entry entry) {
                        Integer population = entry.getValue(1).toString().split(" ").length;
                        return population.intValue() < 6;
                    }
                };
                break;
        }
        orden.setSortKeys(Arrays.asList(new SortKey(columnaOrden, SortOrder.ASCENDING)));
        //orden.setRowFilter(RowFilter.numberFilter(RowFilter.ComparisonType.AFTER, 5, 1));
        orden.setRowFilter(filter);
        orden.sort(); //sorting programatically
    }//GEN-LAST:event_jBOperationsActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(frame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new frame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBOperations;
    private javax.swing.JComboBox jFilterScrap;
    private javax.swing.JLabel jLFilter;
    private javax.swing.JLabel jLSort;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton jScrapButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JComboBox jSortScrap;
    private javax.swing.JTextField jTextUrlScrap;
    private javax.swing.JTable scrappingTable;
    // End of variables declaration//GEN-END:variables
}
